version: "3.7"
services:
  php:
    build:
      args:
        user: dummy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    #image: travellist
    container_name: php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports: 
      - 9000:9000
    networks:
      - cecy
  postgresdb:
    image: postgres:10.13-alpine
    container_name: postgresdb
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 1234
      TZ: America/Guayaquil
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5436:5432
    networks:
      - cecy    
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/html
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cecy
volumes:
  postgres:
    # external: true
networks:
  cecy:
    driver: bridge
